### ISSUE TITLE
returns 0 (success) when service does not exist

### ISSUE THREAD

**Issue by rally25rs** [groundnuty/k8s-wait-for#18]
I stumbled across this issue when I was not passing a `--namespace ...` to the script args...

My init pods were reporting success

```
    state:
      terminated:
        containerID: docker://754eff26e250a9cab94d6a5f49e118bb8975fe93807bc05cbae4bcec6104f722
        exitCode: 0
        finishedAt: "2019-11-14T20:39:09Z"
        reason: Completed
        startedAt: "2019-11-14T20:39:08Z"
```

and the logs from the init container contained

```
parse error: Invalid numeric literal at line 1, column 6
service qa-postgres  is ready.
```

In reality, it was querying a service that does not exist. The output from the `kubectl` command would have been:

```
$ kubectl get service "qa-postgres" -ojson
Error from server (NotFound): services "qa-postgres" not found
```

which when piped to `jq` results in:

```
$ kubectl get service "qa-postgres" -ojson 2>&1 |  jq -cr
parse error: Invalid numeric literal at line 1, column 6
```

however that failure (as seen in the pod log output) results in the sh script returning 0 (success)

It should cause the init pod to fail.

-----

The above is true whenever `kubectl` outputs non-json.

```
/usr/local/bin # kubectl get pods -n qa
Error from server (Forbidden): pods is forbidden: User "system:serviceaccount:qa:default" cannot list resource "pods" in API group "" in the namespace "qa"

/usr/local/bin # wait_for.sh service qa-postgress -n qa && echo "*** returns success"
parse error: Invalid numeric literal at line 1, column 6
[2019-11-14 23:12:49] service qa-postgress is ready.
*** returns success
```
