### ISSUE TITLE
wait-for.sh job never finishes if the job fails (even if it re-runs and completed)

### ISSUE THREAD

**Issue by mmerickel** [groundnuty/k8s-wait-for#45]
I've got a job that normally succeeds and we don't see any problems with k8s-wait-for. However, I'm observing a case where sometimes the job will fail and restart a new job. The metadata on the job ends up here:

```yaml
status:
  completionTime: "2022-03-03T01:25:56Z"
  conditions:
  - lastProbeTime: "2022-03-03T01:25:56Z"
    lastTransitionTime: "2022-03-03T01:25:56Z"
    status: "True"
    type: Complete
  failed: 1
  startTime: "2022-03-03T01:25:14Z"
  succeeded: 1
```

You can see it completed but has one failure. This is fine because the job only needs to succeed once. However right now k8s-wait-for does not consider this ok and continues to spin forever.
