### ISSUE TITLE
Wait for job does not work as expected

### ISSUE THREAD

**Issue by fdutton** [groundnuty/k8s-wait-for#60]
I was expecting for this app to wait until a job completed successfully but it only waited for the job to be ready. Am I misunderstanding something?

This is a portion of my deployment resource and I have verified that my job runs to completion and exits with a status code of 0.
```
initContainers:
  - name: data-migration-init
    image: 'groundnuty/k8s-wait-for:v1.7'
    args:
      - job
      - my-data-migration-job
```
