### ISSUE TITLE
cannot get resource "jobs" in API group "batch" in the namespace "default"

### ISSUE THREAD

**Issue by cfra** [groundnuty/k8s-wait-for#66]
This seems similar to #39, however this issue provides no solution.

I am running `k8s-wait-for` as an init container in a deployment, waiting for a job to complete.

The container starts fine, but then exits with: 

```
Error from server (Forbidden): jobs.batch "app-migration-a4c7915a7495153bcae396e7bd9e3d66c" is forbidden: User "system:serviceaccount:default:default" cannot get resource "jobs" in API group "batch" in the namespace "default"
```

It seems to me like the container with wait-for is lacking the required permissions to access the API with kubectl.

However, I was unable to find any information in the documentation on how to set up proper credentials.

**Comment by cfra** [comment]
To provide a bit more info than in #39 the proper solution seems to configure a service account with the appropriate permissions:

```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-app
  namespace: default
rules:
  - verbs:
      - list
      - watch
      - get
    apiGroups:
      - batch
    resources:
      - jobs
    resourceNames:
      - my-app-migration-3bd734abb2cda61f3545529f3dca40401
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: my-app
  namespace: default
automountServiceAccountToken: true
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-app
subjects:
  - kind: ServiceAccount
    name: my-app
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-app
```

In the template of the deployment where I am running the `k8s-wait-for` container, I can now set the service account to `my-app` and get the proper permissions.
